import { cpSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = dirname(fileURLToPath(import.meta.url));
const runtime = resolve(root, 'runtime');
const metadata = JSON.parse(readFileSync(resolve(root, 'package.json')));
const manifest = JSON.parse(readFileSync(resolve(root, 'opsle-capability.json')));
if (metadata.version !== manifest.version || manifest.default_enabled !== false) {
  throw new Error('Package/manifest versions must agree and installation must default to disabled.');
}
rmSync(runtime, { recursive: true, force: true });
mkdirSync(runtime, { recursive: true });
cpSync(resolve(root, 'src'), runtime, { recursive: true });
cpSync(resolve(root, '../../src'), resolve(runtime, 'core'), { recursive: true });
cpSync(resolve(root, '../../schemas/plan-v2.schema.json'), resolve(root, 'schemas/plan-v2.schema.json'));
cpSync(resolve(root, '../../LICENSE'), resolve(root, 'LICENSE'));
const hashes = {};
function collect(directory) {
  for (const entry of readdirSync(resolve(root, directory), { withFileTypes: true }).sort((a,b) => a.name.localeCompare(b.name))) {
    const path = `${directory}/${entry.name}`;
    if (entry.isDirectory()) collect(path);
    else hashes[path] = createHash('sha256').update(readFileSync(resolve(root, path))).digest('hex');
  }
}
collect('runtime'); collect('schemas');
const identity = `sha256:${createHash('sha256').update(JSON.stringify(hashes)).digest('hex')}`;
writeFileSync(resolve(root, 'adapter.js'), `// Generated by build.mjs. Runtime bytes are pinned to this trusted entry point.
import { readFileSync, realpathSync, lstatSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
const hashes = ${JSON.stringify(hashes, null, 2)};
const packageIdentity = ${JSON.stringify(identity)};
function integrity() {
  const root = realpathSync(fileURLToPath(new URL('.', import.meta.url)));
  for (const [path, expected] of Object.entries(hashes)) {
    const file = fileURLToPath(new URL(path, import.meta.url));
    if (lstatSync(file).isSymbolicLink() || !realpathSync(file).startsWith(root + '/')
      || createHash('sha256').update(readFileSync(file)).digest('hex') !== expected) {
      throw new Error('Capability installation changed: ' + path);
    }
  }
}
export async function createCapability(context) {
  integrity();
  const { createAdapter } = await import('./runtime/adapter.js');
  const adapter = createAdapter(context, packageIdentity);
  return {
    health() { integrity(); return { available: true, detail: null }; },
    invoke(hook, payload) { integrity(); return adapter.invoke(hook, payload); },
  };
}
`);
